
[tcp]
address = "localhost:3030"
message_size = 5

[tcp.schedule]
start_req_per_sec = 5
stop_req_per_sec = 100
steps = 5
secs_per_step = 5

[websocket]
address = "ws://localhost:9001/socket"
message_size = 5

[websocket.schedule]
start_req_per_sec = 5
stop_req_per_sec = 1000
steps = 5
secs_per_step = 5

[mqtt]
address = "localhost:1883"
message_size = 5

[mqtt.schedule]
start_req_per_sec = 5
stop_req_per_sec = 1000
steps = 5
secs_per_step = 5

[opcua]
address = "localhost:1883"
message_size = 5

[opcua.schedule]
start_req_per_sec = 5
stop_req_per_sec = 1000
steps = 5
secs_per_step = 5
